const {PGlite} = await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
const ids={clinician:'10000000-0000-0000-0000-000000000001',patient:'10000000-0000-0000-0000-000000000002',outsider:'10000000-0000-0000-0000-000000000003',admin:'10000000-0000-0000-0000-000000000004',record:'20000000-0000-0000-0000-000000000001',episode:'30000000-0000-0000-0000-000000000001',review:'40000000-0000-0000-0000-000000000001'};
await db.exec(`create role anon; create role authenticated; create schema auth;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth to authenticated;
create table profiles(id uuid primary key,role text);create table patients(id uuid primary key,clinician_id uuid,patient_profile_id uuid);
create table episodes(id uuid primary key,patient_id uuid);
create table clinical_decisions(id uuid primary key,patient_id uuid,episode_id uuid,clinician_id uuid,decision_type text,rationale text,created_at timestamptz default now());
create table home_programs(id uuid primary key,episode_id uuid,status text,patient_explanation text,updated_at timestamptz default now());create table home_program_exercises(id uuid primary key,home_program_id uuid,sort_order integer);
create table daily_checkins(id uuid primary key,patient_id uuid,created_at timestamptz default now());
grant select,insert on all tables in schema public to authenticated;`);
await db.exec(fs.readFileSync('supabase/migrations/20260920190303_clinical_engine_pilot.sql','utf8'));
for(const [name,id]of Object.entries(ids).slice(0,4))await db.query('insert into profiles values($1,$2)',[id,name==='outsider'?'clinician':name]);
await db.query('insert into patients values($1,$2,$3)',[ids.record,ids.clinician,ids.patient]);await db.query('insert into episodes values($1,$2)',[ids.episode,ids.record]);
const as=async id=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
const save=async(id=ids.review,disposition='accepted',status='evaluated')=>db.query('select record_engine_review($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[id,ids.record,ids.episode,'continue','Synthetic review',{version:'0.1-integration.1',status,ruleId:'v0.1.maintain'}, {},disposition,'','']);
await as(ids.clinician);await save();assert.equal((await db.query('select * from clinical_engine_reviews')).rows.length,1);
for(const actor of ['patient','outsider','admin']) {await as(ids[actor]);assert.equal((await db.query('select * from clinical_engine_reviews')).rows.length,0,actor+' read');await assert.rejects(save('40000000-0000-0000-0000-000000000002'));}
await as(ids.clinician);await assert.rejects(db.query('update clinical_engine_reviews set disposition=$1',['rejected']));
await assert.rejects(save('40000000-0000-0000-0000-000000000003','accepted','missing_information'));
assert.equal((await db.query('select * from clinical_decisions')).rows.length,1,'failed review atomicity');
await assert.rejects(db.query('select get_engine_pilot_analytics(30)'));
await as(ids.admin);const result=(await db.query('select get_engine_pilot_analytics(30) as a')).rows[0].a;assert.equal(result.accepted,1);assert(!JSON.stringify(result).includes(ids.record));
await db.exec('reset role');await db.query("insert into daily_checkins values(gen_random_uuid(),$1,now()+interval '1 second')",[ids.record]);
await as(ids.admin);assert.equal((await db.query('select get_engine_pilot_analytics(30) as a')).rows[0].a.withSubsequentResponse,1);
await as(ids.clinician);await db.exec('reset role');await db.query('update patients set clinician_id=$1 where id=$2',[ids.outsider,ids.record]);await as(ids.clinician);assert.equal((await db.query('select * from clinical_engine_reviews')).rows.length,0,'relationship revoked');
await db.exec('reset role');await db.query('update patients set clinician_id=$1 where id=$2',[ids.clinician,ids.record]);
const programId='50000000-0000-0000-0000-000000000001';
await db.query("insert into home_programs(id,episode_id,status) values($1,$2,'active')",[programId,ids.episode]);
await db.exec('grant update on home_programs to authenticated');
await as(ids.clinician);
const version=(await db.query('select updated_at from home_programs where id=$1',[programId])).rows[0].updated_at;
await db.query('select publish_care_guidance($1,$2,$3,$4,gen_random_uuid())',[ids.record,programId,version,'Approved synthetic guidance']);
await assert.rejects(db.query('select publish_care_guidance($1,$2,$3,$4,gen_random_uuid())',[ids.record,programId,version,'Stale guidance']));
assert((await db.query('select * from engine_program_changes')).rows.some(r=>r.review_id===ids.review && r.after_value?.patient_explanation==='Approved synthetic guidance'));
await as(ids.patient);assert.equal((await db.query('select * from engine_program_changes')).rows.length,0);assert.equal((await db.query('select * from care_messages')).rows.length,1);
await db.query("insert into care_messages(patient_id,author_id,body,kind) values($1,$2,'Patient reply','patient_message')",[ids.record,ids.patient]);
await assert.rejects(db.query("insert into care_messages(patient_id,author_id,body,kind) values($1,$2,'Forged approval','approved_guidance')",[ids.record,ids.patient]));
for(const actor of ['outsider','admin']){await as(ids[actor]);assert.equal((await db.query('select * from care_messages')).rows.length,0);await assert.rejects(db.query("insert into care_messages(patient_id,author_id,body,kind) values($1,$2,'Unauthorized','clinician_message')",[ids.record,ids[actor]]));}
console.log('PASS: approved guidance history, stale publication blocked, patient reply, impersonation blocked, unrelated clinician/admin messages excluded.');
console.log('PASS: treating clinician write/read, patient/outsider/admin exclusion, immutable evaluations, transaction rollback, aggregate-only founder access, subsequent response linkage, relationship revocation.');
await db.close();
