const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import { createClient } from '@supabase/supabase-js';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const fixture=JSON.parse(fs.readFileSync(process.env.TEST_FIXTURE_PATH || 'work/test-accounts.json'));
const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
if (!url || !key) throw new Error('Supabase test environment is required');
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:3000';
const checks=[];let browser; const guidance='SYNTHETIC E2E clinician-approved update '+Date.now()+': use revised dosage.';
const pass=name=>{checks.push({name,status:'PASS'});console.log('PASS:',name)};
async function api(role){const user=fixture.users.find(u=>u.role===role);const c=createClient(url,key,{auth:{persistSession:false}});const r=await c.auth.signInWithPassword({email:user.email,password:fixture.password});if(r.error)throw r.error;return c;}
async function login(page,role){const u=fixture.users.find(u=>u.role===role);await page.goto(base+'/login');await page.getByLabel('Email',{exact:true}).fill(u.email);await page.getByLabel('Password',{exact:true}).fill(fixture.password);await page.getByRole('button',{name:'Log in',exact:true}).click();await page.waitForURL(role==='patient'?'**/patient':'**/dashboard',{timeout:60000});}
(async()=>{
 browser=await chromium.launch({channel:'chrome',headless:true});
 const pt=await api('clinician'), patientApi=await api('patient'), outsider=await api('outsider');pass('Three independent real Supabase password logins');
 const pc=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const patient=await pc.newPage();const errors=[];patient.on('pageerror',e=>errors.push(e.message));
 await patient.goto(base+'/patient');await patient.getByText('Secure session required.').waitFor();pass('Fresh browser denies unauthenticated patient data');
 const linked=await pt.from('patients').select('patient_profile_id').eq('id',fixture.patientId).single();
 if(!linked.data.patient_profile_id){const invite=await pt.rpc('create_patient_invite',{p_patient_id:fixture.patientId});if(invite.error)throw invite.error;await patient.goto(base+'/invite?token='+encodeURIComponent(invite.data)+'&mode=signin');await patient.getByRole('link',{name:/log in|sign in/i}).first().click();await patient.getByLabel('Email',{exact:true}).fill(fixture.users[1].email);await patient.getByLabel('Password',{exact:true}).fill(fixture.password);await patient.getByRole('button',{name:'Log in',exact:true}).click();await patient.waitForURL('**/patient',{timeout:60000});pass('Fresh patient claims clinician-generated invitation through login');}
 else await login(patient,'patient');
 await patient.getByText('SYNTHETIC PWA movement plan',{exact:true}).waitFor({timeout:60000});pass('Patient Today shows assigned program');
 await patient.getByRole('navigation',{name:'Patient app navigation'}).getByRole('link',{name:'Program',exact:true}).click();await patient.getByRole('button',{name:"Start today's program"}).click();
 const cards=patient.locator('.patient-exercise-entry');await cards.nth(2).waitFor();
 for(let i=0;i<3;i++){await cards.nth(i).getByRole('button',{name:['Completed','Partially completed','Skipped'][i],exact:true}).click();await cards.nth(i).getByLabel('Difficulty',{exact:true}).selectOption(i===1?'too_hard':'appropriate');}
 await patient.getByRole('button',{name:'Worse',exact:true}).click();await patient.getByLabel('Pain after').fill('4');await patient.getByLabel('Anything your therapist should know?').fill('SYNTHETIC E2E: knee felt harder during the second exercise.');
 await patient.getByRole('button',{name:'Finish today’s program',exact:true}).click();await patient.getByText('Your session and feedback are saved.',{exact:false}).waitFor({timeout:60000});
 const logs=await patientApi.from('exercise_adherence_logs').select('completion_status,session_id').eq('patient_id',fixture.patientId).order('created_at',{ascending:false}).limit(3);assert.deepEqual(new Set(logs.data.map(x=>x.completion_status)),new Set(['completed','partial','skipped']));pass('Completed/partial/skipped and feedback persisted in real database');
 await patient.screenshot({path:'work/patient-session-mobile.png',fullPage:true});
 assert.equal(await patient.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);pass('Patient program fits 390px mobile viewport');
 const cc=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const clinician=await cc.newPage();clinician.on('pageerror',e=>errors.push(e.message));await login(clinician,'clinician');
 await clinician.getByText('Patient feedback to review',{exact:false}).first().waitFor({timeout:60000});pass('Clinician Today inbox receives synthetic feedback');
 await clinician.goto(base+'/patients/'+fixture.patientId);await clinician.getByRole('heading',{name:'Since Last Visit',exact:true}).waitFor();await clinician.getByText('SYNTHETIC E2E: knee felt harder during the second exercise.',{exact:false}).first().waitFor();pass('Patient Workspace shows Since Last Visit and patient comment');
 await clinician.screenshot({path:'work/clinician-workspace-mobile.png',fullPage:true});
 await patient.goto(base+'/patient/care');await clinician.goto(base+'/patients/'+fixture.patientId+'/decision');await clinician.getByLabel('Patient-facing guidance').fill(guidance);assert.equal(await clinician.getByRole('button',{name:'Approve and publish guidance'}).isEnabled(),false);await clinician.getByRole('checkbox').check();await clinician.getByRole('button',{name:'Approve and publish guidance'}).click();await clinician.getByText('Approved guidance saved',{exact:false}).waitFor({timeout:60000});pass('Explicit clinician approval required before publishing guidance');
 await patient.getByText(guidance,{exact:true}).waitFor({timeout:60000});pass('Patient sees approved guidance through automatic Care refresh without reload'); await clinician.getByLabel('Review rationale').fill('SYNTHETIC E2E review: considered all submitted activity.');await clinician.getByRole('button',{name:'Mark feedback reviewed'}).click();await clinician.getByText('Review recorded. Return to Today to see the updated inbox.').waitFor();pass('Clinician records review without sending automatic advice');
 await clinician.goto(base+'/program-builder/'+fixture.patientId);await clinician.getByRole('button',{name:/Save Program/i}).waitFor({timeout:60000});
 // Use the actual dosage input label from the program builder.
 const sets=clinician.getByLabel('Sets',{exact:true});await sets.first().fill('1');await clinician.getByRole('button',{name:/Save Program/i}).click();await clinician.getByText('Program saved.',{exact:false}).first().waitFor({timeout:60000});
 await patient.goto(base+'/patient/program');await patient.getByRole('button',{name:"Start today's program"}).click();await patient.getByText(/1 sets/).first().waitFor();pass('Clinician program dosage update reaches patient');
 await clinician.locator('.more-navigation summary').click();for(const name of ['Programs','Exercise Library','Schedule','Analytics','Care Team','Settings'])assert.equal(await clinician.locator('.more-menu').getByRole('link',{name,exact:true}).isVisible(),true);assert.equal(await clinician.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert(await clinician.locator('.sidebar .nav').evaluate(el=>Math.abs(el.getBoundingClientRect().bottom-innerHeight)<2));pass('Clinician mobile navigation contains Today/Patients/Messages/More and required menu');
 const second=await browser.newContext({viewport:{width:1280,height:800}});const secondPage=await second.newPage();await login(secondPage,'patient');await secondPage.getByText('SYNTHETIC PWA movement plan',{exact:true}).waitFor();await secondPage.goto(base+'/login');await secondPage.waitForURL('**/patient');pass('Second independent patient session and home-screen session resume');
 for(const table of ['patients','daily_checkins','exercise_adherence_logs']){const r=await outsider.from(table).select('id').eq(table==='patients'?'id':'patient_id',fixture.patientId);assert.ifError(r.error);assert.equal(r.data.length,0);}const program=await outsider.from('home_programs').select('id').eq('id',fixture.programId);assert.equal(program.data.length,0);
 const deny=await outsider.from('home_programs').update({patient_explanation:'UNAUTHORIZED'}).eq('id',fixture.programId).select('id');assert.equal(deny.data?.length||0,0);const patientDeny=await patientApi.from('home_programs').update({patient_explanation:'UNAUTHORIZED PATIENT'}).eq('id',fixture.programId).select('id');assert.equal(patientDeny.data?.length||0,0);pass('RLS denies unrelated clinician reads/updates and patient treatment edits');
 const manifest=await (await patient.request.get(base+'/manifest.webmanifest')).json();assert.equal(manifest.display,'standalone');assert.equal(manifest.icons.length,3);for(const icon of manifest.icons)assert.equal((await patient.request.get(base+icon.src)).status(),200);await patient.evaluate(()=>navigator.serviceWorker.ready);pass('Install manifest, icon assets and service worker registration');
 const cached=await patient.evaluate(async()=>{const keys=await caches.keys();return (await Promise.all(keys.map(async k=>(await (await caches.open(k)).keys()).map(r=>new URL(r.url).pathname)))).flat()});assert(cached.every(p=>p==='/offline.html'||p.startsWith('/icons/')));pass('Offline cache contains only public install assets');
 await pc.setOffline(true);await patient.goto(base+'/patient/care');await patient.getByRole('heading',{name:'Let’s reconnect.'}).waitFor();await pc.setOffline(false);pass('Offline navigation gives honest reconnect screen');
 assert.deepEqual(errors,[]);pass('No browser runtime errors in patient and clinician workflows');
 fs.writeFileSync('work/e2e-results.json',JSON.stringify({base,checks},null,2));
})().catch(async e=>{console.error(e);fs.writeFileSync('work/e2e-results.json',JSON.stringify({base,checks,failure:e.message},null,2));process.exitCode=1;}).finally(async()=>{await browser?.close()});
