// Live acceptance uses only explicitly synthetic identities/cases.
import fs from 'node:fs';import assert from 'node:assert/strict';import {createClient} from '@supabase/supabase-js';
const f=JSON.parse(fs.readFileSync('work/followup-fixture.json'));
const base=process.env.TEST_BASE_URL||'http://localhost:3104';
async function api(role){const u=f.users.find(x=>x.role===role);const c=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false}});const r=await c.auth.signInWithPassword({email:u.email,password:f.password});if(r.error)throw r.error;return c;}
const pt=await api('clinician'),pa=await api('patient'),outsider=await api('outsider');
if(process.argv.includes('--seed')){
 const insert=async(table,row)=>{const r=await pt.from(table).insert(row).select().single();if(r.error)throw new Error(table+': '+r.error.message);return r.data;};
 const past=new Date(Date.now()-96*3600000).toISOString();
 const p=await insert('patients',{display_name:'SYNTHETIC Followup Acceptance',clinician_id:f.users[0].id,patient_profile_id:f.users[1].id,status:'active'});
 const e=await insert('episodes',{patient_id:p.id,title:'SYNTHETIC followup episode',status:'active',created_at:past});
 const h=await insert('home_programs',{episode_id:e.id,name:'SYNTHETIC program',status:'active',assigned_at:past,created_at:past});
 const x=await insert('exercises',{clinician_id:f.users[0].id,name:'SYNTHETIC sit to stand',video_url:'https://www.youtube.com/watch?v=dQw4w9WgXcQ',patient_instructions:'Synthetic test instructions'});
 const hx=await insert('home_program_exercises',{home_program_id:h.id,exercise_id:x.id,dosage_sets:'2',dosage_reps:'8',frequency:'3 days/week',sort_order:0});
 f.case={p,e,h,x,hx};fs.writeFileSync('work/followup-fixture.json',JSON.stringify(f),{mode:0o600});console.log('Synthetic case created:',p.id);process.exit(0);
}
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({channel:'chrome',headless:true}),checks=[],errors=[];const pass=s=>{checks.push(s);console.log('PASS:',s);};
try{
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 async function login(page,role){const u=f.users.find(x=>x.role===role);await page.goto(base+'/login');await page.getByLabel('Email',{exact:true}).fill(u.email);await page.getByLabel('Password',{exact:true}).fill(f.password);await page.getByRole('button',{name:'Log in',exact:true}).click();await page.waitForURL(role==='patient'?'**/patient':'**/dashboard',{timeout:60000});}
 await login(page,'patient');if(!process.env.SKIP_INACTIVITY) {await page.getByRole('heading',{name:'Ready when you are',exact:true}).waitFor();await page.getByLabel('Would anything help you get back to your program?').selectOption('offline');await page.getByRole('button',{name:'Save check-in',exact:true}).click();
 await page.waitForTimeout(1200);let r=await pa.from('patient_followups').select('*').eq('patient_id',f.case.p.id).eq('kind','inactivity');assert.equal(r.data.at(-1).status,'answered');pass('Scheduled inactivity check-in visible and answer saved on mobile');}
 await page.goto(base+'/patient/program');await page.getByRole('button',{name:"Start today's program"}).click();await page.getByRole('button',{name:'Completed',exact:true}).click();await page.getByLabel('Difficulty',{exact:true}).selectOption('too_hard');await page.getByLabel('What made it difficult? (optional)').selectOption('instructions');await page.getByLabel('Did this increase your symptoms? (optional)').selectOption('little');await page.getByLabel('How are those symptoms now? (optional)').selectOption('settled');
 await page.getByRole('button',{name:'Load video demonstration'}).click();assert.equal(await page.locator('iframe').count(),1);await page.getByRole('button',{name:'Finish and share feedback',exact:true}).click();await page.getByRole('button',{name:'Better',exact:true}).click();await page.getByLabel('Anything your therapist should know?').fill('SYNTHETIC follow-up feedback');await page.getByRole('button',{name:'Finish today’s program',exact:true}).click();await page.getByText('Your session and feedback are saved.',{exact:false}).waitFor();
 const logs=await pa.from('exercise_adherence_logs').select('*').eq('home_program_id',f.case.h.id);assert.equal(logs.data.at(-1).difficulty_reason,'instructions');assert.equal(logs.data.at(-1).symptom_recovery,'settled');pass('Program, video and contextual difficulty/symptom/recovery feedback persist');
 if(!process.env.SKIP_RESPONSE) {await page.goto(base+'/patient');await page.getByLabel('How is the daily activity you are working toward?').selectOption('improving');assert.equal(await page.getByLabel('Compared with your last check-in, how are your symptoms?').count(),0);await page.getByRole('button',{name:'Save check-in',exact:true}).click();await page.waitForTimeout(1200);
 const response=await pa.from('daily_checkins').select('function_direction').eq('patient_id',f.case.p.id).eq('function_direction','improving');assert(response.data.length>0);pass('Only missing function is asked, then saved as structured evidence');}
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'work/followup-patient-mobile.png',fullPage:true});
 const denied=await outsider.from('patient_followups').select('*').eq('patient_id',f.case.p.id);assert.deepEqual(denied.data,[]);assert.deepEqual((await outsider.from('patient_followup_state').select('*').eq('patient_id',f.case.p.id)).data,[]);pass('Live RLS hides follow-up and decision state from unrelated clinician');
 const cc=await browser.newContext({viewport:{width:1280,height:900}}),cp=await cc.newPage();cp.on('pageerror',e=>errors.push(e.message));await login(cp,'clinician');await cp.getByRole('heading',{name:'Recommendations to Review'}).waitFor();await cp.getByText('SYNTHETIC Followup Acceptance',{exact:true}).first().click();await cp.getByRole('heading',{name:'Move Free analysis and recommendation'}).waitFor();assert.equal(await cp.getByLabel('Your assessment of this suggestion').count(),0);pass('Today opens correct Summary; incomplete evaluation cannot be approved');
 await cp.getByRole('navigation',{name:'Patient workspace tabs'}).getByRole('link',{name:'Patient Log',exact:true}).click();await cp.getByLabel('Show',{exact:true}).selectOption('followups');await cp.getByText('Patient check-in response',{exact:true}).first().waitFor();pass('Patient Log shows automatic question and response');
 await cp.getByRole('navigation',{name:'Patient workspace tabs'}).getByRole('link',{name:'Summary',exact:true}).click();await cp.getByLabel('Review rationale').fill('SYNTHETIC independent clinician review; examination still needed');await cp.getByRole('button',{name:'Mark feedback reviewed',exact:true}).click();await cp.getByText('Review recorded. Return to Today to see the updated inbox.',{exact:true}).waitFor();const reviews=await pt.from('clinical_engine_reviews').select('disposition').eq('patient_id',f.case.p.id).order('created_at',{ascending:false});assert.equal(reviews.data[0].disposition,'not_evaluated');pass('Incomplete case can record independent clinician decision without approving an engine suggestion');
 const msg=await pa.from('care_messages').insert({id:crypto.randomUUID(),patient_id:f.case.p.id,author_id:f.users[1].id,kind:'patient_message',body:'SYNTHETIC check-in message'});assert.equal(msg.error,null);assert((await pt.from('care_messages').select('id').eq('patient_id',f.case.p.id)).data.length>0);pass('Existing patient-to-clinician message path works');
 await cp.screenshot({path:'work/followup-clinician-log.png',fullPage:true});assert.deepEqual(errors,[]);pass('No browser runtime errors');
 fs.writeFileSync('work/followup-browser-results.json',JSON.stringify({base,checks},null,2));
}finally{await browser.close();}
