import fs from 'node:fs';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();
const schema=JSON.parse(fs.readFileSync('tests/fixtures/pre-pilot-authorization-schema.json'));
const quote=s=>'"'+s.replaceAll('"','""')+'"';
await db.exec(`create role anon;create role authenticated;create schema auth;create schema private;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,private to authenticated;`);
for(const table of new Set(schema.columns.map(c=>c.table))){
 const cols=schema.columns.filter(c=>c.table===table).map(c=>`${quote(c.column)} ${c.type.startsWith('_')?c.type.slice(1)+'[]':c.type}${c.default?' default '+c.default:''}${c.column==='id'?' primary key':''}`);
 await db.exec(`create table public.${quote(table)}(${cols.join(',')});alter table public.${quote(table)} enable row level security;`);
}
for(const f of schema.functions.sort((a,b)=>Number(!a.includes('FUNCTION private.'))-Number(!b.includes('FUNCTION private.'))))await db.exec(f);
await db.exec('grant all on all tables in schema public to authenticated;grant execute on all functions in schema private to authenticated;');
for(const p of schema.policies)await db.exec(`create policy ${quote(p.policyname)} on public.${quote(p.tablename)} as ${p.permissive} for ${p.cmd} to ${p.roles.map(quote).join(',')}${p.qual?' using ('+p.qual+')':''}${p.with_check?' with check ('+p.with_check+')':''};`);
await db.exec(fs.readFileSync('supabase/migrations/20260921235753_enforce_pilot_relationship_authorization.sql','utf8'));
await db.exec(`create table public.clinical_engine_reviews(id uuid primary key,patient_id uuid,engine_result jsonb,disposition text);`);
await db.exec(fs.readFileSync('supabase/migrations/20261004115925_stage1_adaptive_followups.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/20261004121415_stage1_followup_schedule.sql','utf8').split('-- Activate after application deployment.')[0]);
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const now=new Date(), ago=h=>new Date(+now-h*3600000).toISOString();
for(const [n,role] of [[1,'clinician'],[2,'patient'],[3,'clinician']])await db.query('insert into profiles(id,role) values($1,$2)',[id(n),role]);
await db.query('insert into patients(id,clinician_id,patient_profile_id,status) values($1,$2,$3,\'active\')',[id(10),id(1),id(2)]);
await db.query('insert into episodes(id,patient_id,status,created_at) values($1,$2,\'active\',$3)',[id(11),id(10),ago(100)]);
await db.query('insert into home_programs(id,episode_id,status,assigned_at,created_at) values($1,$2,\'active\',$3,$3)',[id(12),id(11),ago(100)]);
await db.query('insert into home_program_exercises(id,home_program_id) values($1,$2)',[id(13),id(12)]);
const run=async t=>db.query('select private.refresh_patient_followups($1,$2)',[id(10),t??now.toISOString()]);
const all=async()=> (await db.query('select * from patient_followups')).rows;
const state=async()=> (await db.query('select * from patient_followup_state')).rows[0];
await db.query("insert into daily_checkins(patient_id,episode_id,created_at,symptom_direction,function_direction) values($1,$2,$3,'unchanged','stable')",[id(10),id(11),ago(71)]);
await run();assert.equal((await all()).length,0);console.log('A: activity within 72h: no reminder');
await run(new Date(+now+3600000).toISOString());assert.equal((await all()).length,1);assert.equal((await all())[0].kind,'inactivity');console.log('B: exactly 72h: one inactivity check-in');
await run(new Date(+now+2*3600000).toISOString());assert.equal((await all()).length,1);
await run(new Date(+now+74*3600000).toISOString());assert.equal((await all()).length,1);assert.equal((await state()).state,'CLINICIAN_REVIEW');console.log('C: repeated runs deduplicated; unanswered escalates');
await db.exec("update patients set status='discharged'");await run();assert.equal((await all())[0].status,'cancelled');assert.equal((await state()).state,'INACTIVE');console.log('D: discharged excluded');
await db.exec("update patients set status='active'; update home_programs set status='archived'");await run();assert.equal((await state()).state,'INACTIVE');console.log('E: no active program excluded');
await db.exec("update home_programs set status='active'; delete from patient_followups; delete from daily_checkins");
await db.query("insert into exercise_adherence_logs(patient_id,home_program_id,completion_status,created_at,performed_at) values($1,$2,'completed',$3,$3)",[id(10),id(12),ago(1)]);
await run();assert.deepEqual((await all())[0].questions,['symptoms','function']);assert.equal((await state()).state,'NEEDS_CHECK_IN');console.log('G: completion without response asks only symptoms/function');
const as=async n=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);await db.exec('set role authenticated');};
const f=(await all())[0];
await as(3);assert.equal((await all()).length,0);assert.equal((await db.query('select * from patient_followup_state')).rows.length,0);
await assert.rejects(db.query('select answer_patient_followup($1,$2)',[f.id,{symptoms:'improving',function:'improving'}]));
await assert.rejects(db.query('select private.run_stage1_followups()'));console.log('K: unrelated clinician denied reads, answer and scheduler invocation');
await as(2);await assert.rejects(db.query('update patient_followups set status=\'answered\''));await assert.rejects(db.query('select answer_patient_followup($1,$2)',[f.id,{symptoms:'improving',function:'improving',newNeuro:'false'}]));
await db.query('select answer_patient_followup($1,$2)',[f.id,{symptoms:'improving',function:'improving'}]);
await db.exec('reset role');assert.equal((await state()).state,'RESPONSE_AVAILABLE');assert.equal((await all())[0].status,'answered');assert.equal((await db.query("select * from daily_checkins where function_direction='improving'")).rows.length,1);console.log('H: answer saved structurally and reevaluated atomically');
await db.exec('delete from patient_followups');
await db.query("insert into clinical_decisions(id,patient_id,episode_id,created_at) values($1,$2,$3,$4)",[id(20),id(10),id(11),ago(0)]);
await db.query("insert into clinical_engine_reviews values($1,$2,$3,'accepted')",[id(20),id(10),{ruleId:'v0.1.safety'}]);
await run(new Date(+now+100*3600000).toISOString());assert.equal((await all()).length,0);assert.equal((await state()).state,'SAFETY_REVIEW');console.log('J: safety takes precedence over inactivity');
await db.close();
