// Live Supabase + browser acceptance. Only fresh, explicitly synthetic identities/cases.
import fs from 'node:fs';import assert from 'node:assert/strict';import {createClient} from '@supabase/supabase-js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const f=JSON.parse(fs.readFileSync('work/lifecycle-accounts.json'));const base=process.env.TEST_BASE_URL||'http://localhost:3012';
const checks=[];const pass=name=>{checks.push(name);console.log('PASS:',name);};
async function api(role){const u=f.users.find(x=>x.role===role),c=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false}});const {error}=await c.auth.signInWithPassword({email:u.email,password:f.password});if(error)throw error;return c;}
const pt=await api('clinician'),patientApi=await api('patient'),outsider=await api('outsider'),admin=await api('admin');pass('Four independent synthetic accounts authenticate');
const insert=async(table,row)=>{const r=await pt.from(table).insert(row).select().single();if(r.error)throw new Error(table+': '+r.error.message);return r.data;};
const cases=process.env.REUSE_CASES?f.cases:{};const stamp=Date.now();
for(const kind of (process.env.REUSE_CASES?[]:['Alert','Review','On Track'])){
 const p=await insert('patients',{display_name:`SYNTHETIC ${kind} ${stamp}`,clinician_id:f.users[0].id,status:'active',goal:'Walk for 30 minutes'});
 const e=await insert('episodes',{patient_id:p.id,title:'SYNTHETIC Knee rehabilitation',status:'active',start_date:'2026-09-01'});
 const g=await insert('goals',{episode_id:e.id,title:'Walk for 30 minutes',baseline_value:'10',current_value:'20',target_value:'30',status:'active'});
 const h=await insert('home_programs',{episode_id:e.id,name:'SYNTHETIC movement plan',status:'active',assigned_at:new Date().toISOString(),patient_explanation:'SYNTHETIC approved exercise plan'});
 const x=await insert('exercises',{clinician_id:f.users[0].id,name:`SYNTHETIC knee exercise ${kind} ${stamp}`,category:'strength',patient_instructions:'Synthetic test movement'});
 const hx=await insert('home_program_exercises',{home_program_id:h.id,exercise_id:x.id,dosage_sets:'2',dosage_reps:'10',frequency:'Daily',sort_order:0});
 const earlier=new Date(Date.now()-600000).toISOString();
 await insert('daily_checkins',{patient_id:p.id,episode_id:e.id,pain_score:kind==='Alert'?8:2,symptom_direction:kind==='Alert'?'worsening':'improving',created_at:earlier,patient_comment:'SYNTHETIC factual check-in'});
 if(kind==='On Track')await insert('clinical_decisions',{patient_id:p.id,episode_id:e.id,clinician_id:f.users[0].id,decision_type:'continue',rationale:'SYNTHETIC clinician reviewed available reports'});
 cases[kind]={p,e,g,h,x,hx};
}
f.cases=cases;fs.writeFileSync('work/lifecycle-accounts.json',JSON.stringify(f));
const current=cases.Alert;
const linked=await pt.from('patients').select('patient_profile_id').eq('id',current.p.id).single();
if(!linked.data.patient_profile_id){
 const invite=await pt.rpc('create_patient_invite',{p_patient_id:current.p.id});if(invite.error)throw invite.error;
 const claim=await patientApi.rpc('claim_patient_invite',{p_token:invite.data});if(claim.error)throw claim.error;
}
pass('Synthetic patient linked through authorized invitation');
const browser=await chromium.launch({channel:'chrome',headless:true});const errors=[];
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 async function login(page,role){const u=f.users.find(x=>x.role===role);await page.goto(base+'/login');await page.getByLabel('Email',{exact:true}).fill(u.email);await page.getByLabel('Password',{exact:true}).fill(f.password);await page.getByRole('button',{name:'Log in',exact:true}).click();await page.waitForURL(role==='patient'?'**/patient':'**/dashboard',{timeout:60000});}
 await login(page,'clinician');await page.getByRole('heading',{name:'Recommendations to Review',exact:true}).waitFor();
 await page.getByText(current.p.display_name,{exact:true}).waitFor();assert.equal(await page.getByText(cases['On Track'].p.display_name,{exact:true}).count(),0);await page.getByText(cases.Review.p.display_name,{exact:true}).waitFor();pass('Today displays Alerts and Review only; On Track is count-only');
 await page.screenshot({path:'work/today-desktop.png',fullPage:true});await page.getByRole('link',{name:`Review ${current.p.display_name}`,exact:true}).click();await page.getByRole('heading',{name:'Move Free analysis and recommendation'}).waitFor();pass('Review opens correct patient Summary with automatic recommendation');
 const tabs=page.getByRole('navigation',{name:'Patient workspace tabs'});assert.deepEqual(await tabs.getByRole('link').allTextContents(),['Summary','Progress','Patient Log','Program']);
 await tabs.getByRole('link',{name:'Progress',exact:true}).click();await page.getByRole('heading',{name:'Goal and function progress'}).waitFor();
 await page.getByRole('navigation',{name:'Patient workspace tabs'}).getByRole('link',{name:'Patient Log',exact:true}).click();await page.getByText('SYNTHETIC factual check-in',{exact:true}).waitFor();await page.getByLabel('Show',{exact:true}).selectOption('exercise');await page.getByText('No entries in this filter.').waitFor();
 await page.getByRole('navigation',{name:'Patient workspace tabs'}).getByRole('link',{name:'Program',exact:true}).click();await page.getByRole('heading',{name:'SYNTHETIC movement plan',exact:true}).waitFor();pass('Four tabs, factual log filters, baseline/current progress and program work');
 await page.getByRole('navigation',{name:'Patient workspace tabs'}).getByRole('link',{name:'Summary',exact:true}).click();await page.getByText('Automatically analyzed data',{exact:true}).first().click();await page.getByRole('heading',{name:'Automatically analyzed data'}).waitFor();
 await page.getByText('Add clinical observation / inspect unavailable information',{exact:true}).click();assert.equal(await page.locator('#engine-newNeuro').inputValue(),'');await page.locator('#engine-newNeuro').selectOption('true');await page.getByText('Refer / urgent escalation',{exact:true}).waitFor();
 await page.getByLabel('Your assessment of this suggestion').selectOption('rejected');await page.getByLabel('Review rationale').fill('SYNTHETIC rejection, clinician decision retained');await page.getByRole('button',{name:'Mark feedback reviewed',exact:true}).click();await page.getByText('Review recorded. Return to Today to see the updated inbox.').waitFor();
 const review=await pt.from('clinical_engine_reviews').select('disposition,source_snapshot').eq('patient_id',current.p.id);assert.equal(review.data.at(-1).disposition,'rejected');assert.equal(review.data.at(-1).source_snapshot.inputProvenance.newNeuro.state,'CLINICIAN-ADDED');pass('Automatic review, unknowns, observation recalculation and clinician rejection persist');
 const pc=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),pp=await pc.newPage();pp.on('pageerror',e=>errors.push(e.message));await login(pp,'patient');await pp.getByRole('navigation',{name:'Patient app navigation'}).getByRole('link',{name:'Program',exact:true}).click();await pp.getByRole('button',{name:"Start today's program"}).click();await pp.getByRole('button',{name:'Completed',exact:true}).click();await pp.getByRole('button',{name:'Finish and share feedback',exact:true}).click();await pp.getByRole('button',{name:'Better',exact:true}).click();await pp.getByLabel('Anything your therapist should know?').fill('SYNTHETIC lifecycle patient feedback');await pp.getByRole('button',{name:'Finish today’s program',exact:true}).click();await pp.getByText('Your session and feedback are saved.',{exact:false}).waitFor();assert.equal(await pp.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);pass('Patient Stage 1 exercise completion and feedback saved on mobile');
 await page.goto(base+'/patients/'+current.p.id);await page.setViewportSize({width:390,height:844});await page.getByRole('heading',{name:current.p.display_name,exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'work/summary-mobile.png',fullPage:true});pass('Clinician mobile Summary fits without horizontal overflow');
 await page.getByText('Case management · Discharge',{exact:true}).click();await page.getByLabel('Discharge reason',{exact:true}).selectOption('Goals met');await page.getByLabel('Final program status',{exact:true}).selectOption('ended');await page.getByLabel('Discharge note / outcomes',{exact:true}).fill('SYNTHETIC goals reached');await page.getByRole('button',{name:'Discharge Case',exact:true}).click();await page.getByText('Discharged case. Clinical history remains available.',{exact:false}).waitFor();
 const events=await pt.from('case_lifecycle_events').select('*').eq('patient_id',current.p.id);assert.equal(events.data.length,1);assert.equal(events.data[0].snapshot.goals[0].id,current.g.id);assert.equal((await pt.from('home_programs').select('status').eq('id',current.h.id).single()).data.status,'archived');assert.equal((await pt.from('goals').select('id').eq('id',current.g.id)).data.length,1);pass('Discharge snapshots goals/program and preserves history');
 await page.goto(base+'/dashboard');await page.getByRole('heading',{name:'Recommendations to Review'}).waitFor();assert.equal(await page.getByText(current.p.display_name,{exact:true}).count(),0);await page.goto(base+'/patients');await page.getByRole('button',{name:/Discharged/}).click();await page.getByText(current.p.display_name,{exact:true}).click();await page.getByText('Discharged case. Clinical history remains available.',{exact:false}).waitFor();pass('Discharged case removed from Today, present in Discharged Patients and viewable');
 await page.getByText('Discharged case · Reactivate Case',{exact:true}).click();await page.getByText('Start New Episode',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Start New Episode',exact:true}).count(),0);pass('Start New Episode honestly unavailable; does not create or mix records');
 await page.getByLabel('Reason for reopening the same case',{exact:true}).fill('SYNTHETIC same knee problem recurring');await page.getByRole('button',{name:'Reactivate Case',exact:true}).click();await page.getByRole('heading',{name:'Move Free analysis and recommendation'}).waitFor();assert.equal((await pt.from('episodes').select('id,status').eq('id',current.e.id).single()).data.status,'active');assert.equal((await pt.from('home_programs').select('status').eq('id',current.h.id).single()).data.status,'archived');pass('Reactivate reopens same episode, requires review and does not restart ended program');
 for(const [role,c]of [['patient',patientApi],['outsider',outsider],['admin',admin]]){const deny=await c.rpc('transition_case',{p_patient_id:current.p.id,p_episode_id:current.e.id,p_action:'discharge',p_reason:'Goals met',p_date:new Date().toLocaleDateString('en-CA'),p_program_plan:'ended',p_note:'SYNTHETIC unauthorized attempt'});assert(deny.error,role);assert.equal((await c.from('case_lifecycle_events').select('id').eq('patient_id',current.p.id)).data.length,0,role);if(role!=='patient')assert.equal((await c.from('episodes').select('id').eq('id',current.e.id)).data.length,0,role);}
 pass('Live RLS denies patient, unrelated clinician and admin lifecycle writes/history; unrelated episode reads denied');
 await page.goto(base+'/patients');await page.getByRole('button',{name:/Active/}).click();await page.getByText(cases['On Track'].p.display_name,{exact:true}).waitFor();pass('On Track patient remains accessible under Active Patients');
 assert.deepEqual(errors,[]);pass('No browser runtime errors');fs.writeFileSync('work/lifecycle-browser-results.json',JSON.stringify({base,checks},null,2));
}finally{await browser.close();}
