// Hosted synthetic-only Stage 2 verification; credentials remain in ignored work/.
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
import {createClient} from '@supabase/supabase-js';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const fixture=JSON.parse(fs.readFileSync('work/test-accounts.json'));
const base=process.env.TEST_BASE_URL;
if(!base)throw Error('TEST_BASE_URL required');
const bucket='exercise-video-preview',checks=[],clients=[],assets=[];
const pass=name=>{checks.push({name,status:'PASS'});console.log('PASS:',name);};
async function api(role){const user=fixture.users.find(x=>x.role===role);const db=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false}});const {error}=await db.auth.signInWithPassword({email:user.email,password:fixture.password});if(error)throw error;clients.push(db);return db;}
async function login(page,role){const user=fixture.users.find(x=>x.role===role);await page.goto(base+'/login');await page.getByLabel('Email',{exact:true}).fill(user.email);await page.getByLabel('Password',{exact:true}).fill(fixture.password);await page.getByRole('button',{name:'Log in',exact:true}).click();await page.waitForURL(role==='patient'?'**/patient':'**/dashboard',{timeout:60000});}
async function play(page){await page.getByRole('button',{name:'Load private video',exact:true}).first().click();const v=page.locator('video').first();await v.waitFor();await v.evaluate(v=>v.play());await page.waitForTimeout(900);assert(await v.evaluate(v=>v.currentTime>0&&!v.error));}
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const [clinicianApi,patientApi,outsider,admin]=await Promise.all(['clinician','patient','outsider','admin'].map(api));
 // Clean interrupted prior runs using only this fixture's assets and owners.
 const previous=await clinicianApi.from('exercise_video_assets').select('*').eq('patient_id',fixture.patientId);
 assert.ifError(previous.error);
 for(const a of previous.data){const owner=a.owner_id===fixture.users.find(x=>x.role==='patient').id?patientApi:clinicianApi;assert.ifError((await owner.rpc('withdraw_exercise_video',{p_id:a.id})).error);assert.ifError((await owner.storage.from(bucket).remove([a.object_path])).error);}
 const cc=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),pc=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 const clinician=await cc.newPage(),patient=await pc.newPage();const errors=[];for(const p of [clinician,patient])p.on('pageerror',e=>errors.push(e.message));
 await login(clinician,'clinician');await login(patient,'patient');
 // Generated pixels only: no people, camera or microphone captured.
 const clip=await clinician.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=320;canvas.height=240;const ctx=canvas.getContext('2d');const stream=canvas.captureStream(10);const recorder=new MediaRecorder(stream,{mimeType:'video/webm'}),chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);const done=new Promise(resolve=>recorder.onstop=resolve);recorder.start();for(let i=0;i<15;i++){ctx.fillStyle=i%2?'#12634c':'#f0dba2';ctx.fillRect(0,0,320,240);ctx.fillStyle='white';ctx.font='24px sans-serif';ctx.fillText('SYNTHETIC VIDEO '+i,15,120);await new Promise(r=>setTimeout(r,100));}recorder.stop();await done;stream.getTracks().forEach(x=>x.stop());return [...new Uint8Array(await new Blob(chunks,{type:'video/webm'}).arrayBuffer())];});
 fs.writeFileSync('work/synthetic-video.webm',Buffer.from(clip));
 await clinician.goto(base+'/patients/'+fixture.patientId+'/videos');await clinician.getByRole('heading',{name:'Personalized exercise videos'}).waitFor();
 await clinician.locator('input[aria-label="Choose video file"]').setInputFiles({name:'invalid.txt',mimeType:'text/plain',buffer:Buffer.from('invalid')});await clinician.getByRole('alert').getByText('Choose an MP4, WebM or MOV video.').waitFor();pass('Mobile upload rejects non-video selection');
 await clinician.locator('input[aria-label="Choose video file"]').setInputFiles('work/synthetic-video.webm');await clinician.getByRole('button',{name:'Upload private draft',exact:true}).click();await clinician.getByText('Video uploaded privately.',{exact:false}).waitFor({timeout:60000});
 let r=await clinicianApi.from('exercise_video_assets').select('*').eq('patient_id',fixture.patientId).eq('kind','demonstration').eq('state','ready').order('created_at',{ascending:false}).limit(1);assert.ifError(r.error);const demo=r.data[0];assert(demo);assets.push({asset:demo,db:clinicianApi});pass('Clinician private upload completes through real Storage and finalize RPC');
 assert.equal((await patientApi.from('exercise_video_assets').select('id').eq('id',demo.id)).data.length,0);assert((await patientApi.storage.from(bucket).createSignedUrl(demo.object_path,60)).error);pass('Patient cannot read draft metadata or obtain a draft playback link');
 for(const db of [outsider,admin]){assert.equal((await db.from('exercise_video_assets').select('id').eq('id',demo.id)).data.length,0);assert((await db.storage.from(bucket).createSignedUrl(demo.object_path,60)).error);assert((await db.rpc('approve_exercise_video',{p_id:demo.id,p_title:'Forged',p_instructions:'Forged',p_cues:''})).error);}pass('Unrelated clinician and admin cannot read/sign/approve the demonstration');
 assert.equal(await clinician.getByRole('button',{name:'Approve for patient',exact:true}).isEnabled(),false);await play(clinician);await clinician.getByLabel('Exercise name',{exact:true}).fill('SYNTHETIC personalized movement');await clinician.getByLabel(/^Instructions/).fill('SYNTHETIC approved: move slowly within your prescribed range.');await clinician.getByLabel(/^Key cues/).fill('SYNTHETIC relaxed shoulders');await clinician.getByRole('checkbox',{name:'I watched this video',exact:false}).check();await clinician.getByRole('button',{name:'Approve for patient',exact:true}).click();await clinician.getByText('Clinician demonstration · Approved',{exact:true}).first().waitFor();pass('Real private playback and explicit reviewed-instructions approval');
 await patient.goto(base+'/patient/program');await patient.getByRole('button',{name:"Start today's program",exact:true}).click();await patient.getByText('SYNTHETIC approved: move slowly within your prescribed range.',{exact:true}).waitFor();await play(patient);pass('Patient program shows clinician-approved personalized instructions and playable private video');
 const publicRead=await fetch(process.env.NEXT_PUBLIC_SUPABASE_URL+'/storage/v1/object/public/'+bucket+'/'+demo.object_path);assert(!publicRead.ok);assert((await clinicianApi.storage.from(bucket).upload(demo.object_path,Buffer.from(clip),{contentType:'video/webm',upsert:true})).error);pass('Public playback and overwriting an approved file are denied');
 await patient.goto(base+'/patient/videos');await patient.getByRole('heading',{name:'Videos for your therapist'}).waitFor();assert.equal(await patient.getByRole('button',{name:'Withdraw video'}).count(),0);await patient.locator('input[aria-label="Choose video file"]').setInputFiles('work/synthetic-video.webm');assert.equal(await patient.getByRole('button',{name:'Share video with my therapist',exact:true}).isEnabled(),false);await patient.getByRole('checkbox',{name:'I choose to share',exact:false}).check();await patient.getByRole('button',{name:'Share video with my therapist',exact:true}).click();await patient.getByText('Your video was shared with your treating clinician.',{exact:false}).waitFor({timeout:60000});
 r=await patientApi.from('exercise_video_assets').select('*').eq('patient_id',fixture.patientId).eq('kind','performance').eq('state','ready').order('created_at',{ascending:false}).limit(1);assert.ifError(r.error);const performance=r.data[0];assets.push({asset:performance,db:patientApi});assert(performance.consented_at&&performance.consent_notice_version==='video-pilot-v1');pass('Optional patient upload requires consent and records its notice version');
 await clinician.reload();await clinician.getByText('Patient recording · Awaiting review',{exact:true}).first().waitFor();const card=clinician.locator('article').filter({hasText:'Patient recording · Awaiting review'}).first();await card.getByRole('button',{name:'Load private video'}).click();await card.locator('video').evaluate(v=>v.play());await clinician.waitForTimeout(900);assert(await card.locator('video').evaluate(v=>v.currentTime>0&&!v.error));pass('Treating clinician plays the patient recording with no automated assessment');
 for(const db of [outsider,admin]){assert.equal((await db.from('exercise_video_assets').select('id').eq('id',performance.id)).data.length,0);assert((await db.storage.from(bucket).createSignedUrl(performance.object_path,60)).error);}assert((await patientApi.rpc('approve_exercise_video',{p_id:performance.id,p_title:'Invalid',p_instructions:'Invalid',p_cues:''})).error);pass('Performance submission remains private and cannot self-approve');
 for(const p of [clinician,patient])assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);pass('Both video workspaces fit 390px mobile touch viewport with no page errors');
 await patient.screenshot({path:'work/stage2-patient-mobile.png',fullPage:true});await clinician.screenshot({path:'work/stage2-clinician-mobile.png',fullPage:true});
 await patient.getByRole('button',{name:'Withdraw video',exact:true}).click();await patient.getByText('Video withdrawn.',{exact:false}).waitFor();assert((await clinicianApi.storage.from(bucket).createSignedUrl(performance.object_path,60)).error);assert((await patientApi.storage.from(bucket).createSignedUrl(performance.object_path,60)).error);pass('Patient withdrawal denies new playback links to both participants');
 for(const {asset,db}of assets){const w=await db.rpc('withdraw_exercise_video',{p_id:asset.id});assert.ifError(w.error);const d=await db.storage.from(bucket).remove([asset.object_path]);assert.ifError(d.error);assert.equal(d.data.length,1,'Storage API cleanup removes actual bytes');}pass('Owners delete withdrawn synthetic video files through Storage API');
}finally{
 fs.writeFileSync('work/stage2-video-test-results.json',JSON.stringify({base,checkedAt:new Date().toISOString(),checks},null,2));
 for(const db of clients)await db.auth.signOut();await browser.close();
}
